LEXICON_RU: dict[str, str] = {
    '/start': '...start',
    '/help': '...help',
    '/start(new)': '...Бот приветствует пользователя и предлагает сыграть в игру "Камень, ножницы, бумага"',
    'other': '...Бот присылает в чат сообщение, что не понимает пользователя.',
    'y_button': 'Давай!',
    'n_button': 'В другой раз',
    'decline_text': 'Хорошо. Если, вдруг, захочешь сыграть - открой клавиатуру и нажми "Давай!"',
    'accept_text': 'Отлично! Делай свой выбор!',
    'paper': 'paper',
    'rock': 'rock',
    'scissors': 'scissors',
    'same_answer': '...same_answer',
    'win': '...win',
    'lose': '...lose',
}
